### ISSUE TITLE
Unknown error: strptime() argument 1 must be str, not int

### ISSUE THREAD

**Issue by udaydeep1992** [vanhbakaa/Fabrika-Friends-Factory#1]
![image](https://github.com/user-attachments/assets/b2b5a6db-3b99-4136-a80a-cbb0081c36e2)

**Comment by udaydeep1992** [comment]
![image](https://github.com/user-attachments/assets/20d9eb3e-aec1-45d1-9d4c-9bdd4ada885b)

**Comment by hasan1818666891** [comment]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/WORK/Fabrika-Friends-Factory/bot/core/tapper.py", line 507, in run
    if self.check_time(self.last_boost_used):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/WORK/Fabrika-Friends-Factory/bot/core/tapper.py", line 307, in check_time
    if convert_to_unix(available_time) < time() - 3600:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/WORK/Fabrika-Friends-Factory/bot/core/tapper.py", line 29, in convert_to_unix
    dt_obj = datetime.strptime(time_stamp, '%Y-%m-%dT%H:%M:%S.%fZ').replace(tzinfo=timezone.utc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not int
```

**Comment by vanhbakaa** [comment]
fixed in newest version
