### ISSUE TITLE
Failed to refresh token: {"message":"Unauthorized","statusCode":401}

### ISSUE THREAD

**Issue by udaydeep1992** [vanhbakaa/Fabrika-Friends-Factory#2]
![image](https://github.com/user-attachments/assets/ba95b49e-f705-4529-84fd-91ac492f2751)

**Comment by vanhbakaa** [comment]
can you show full log from start

**Comment by udaydeep1992** [comment]
![image](https://github.com/user-attachments/assets/da3e8586-a730-403f-90b4-64a0246e39a0)

**Comment by vanhbakaa** [comment]
are you using query ro run ?

**Comment by udaydeep1992** [comment]
> are you using query ro run ?

Using Session
![image](https://github.com/user-attachments/assets/95da15f7-911f-4b6f-82bf-b3d582d3fb6e)

**Comment by vanhbakaa** [comment]
restart the bot it would work fine

**Comment by udaydeep1992** [comment]
Updated with new version and restarted, let see now
thank you for your active development

**Comment by DvoeglazovIlya** [comment]
```
2024-09-30 19:08:07 | WARNING  | 389 - olga | Failed to refresh token: {"message":"Unauthorized","statusCode":401}
2024-09-30 19:08:07 | WARNING  | 389 - olga | Failed to refresh token: {"message":"Unauthorized","statusCode":401}
Traceback (most recent call last):
  File "/app/bot/core/tapper.py", line 472, in run
    task_list = self.fetch_tasks(session)
  File "/app/bot/core/tapper.py", line 267, in fetch_tasks
    self.fetch_tasks(session)
  File "/app/bot/core/tapper.py", line 267, in fetch_tasks
    self.fetch_tasks(session)
  File "/app/bot/core/tapper.py", line 267, in fetch_tasks
    self.fetch_tasks(session)
  [Previous line repeated 166 more times]
  File "/app/bot/core/tapper.py", line 266, in fetch_tasks
    self.refresh_token(session)
  File "/app/bot/core/tapper.py", line 389, in refresh_token
    logger.warning(f"{self.session_name} | <yellow>Failed to refresh token:</yellow> {res.text}")
  File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 2052, in warning
    __self._log("WARNING", False, __self._options, __message, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
  File "/usr/local/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "/usr/local/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<title>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
Traceback (most recent call last):
  File "/app/bot/core/tapper.py", line 472, in run
    task_list = self.fetch_tasks(session)
  File "/app/bot/core/tapper.py", line 267, in fetch_tasks
    self.fetch_tasks(session)
  File "/app/bot/core/tapper.py", line 267, in fetch_tasks
    self.fetch_tasks(session)
  File "/app/bot/core/tapper.py", line 267, in fetch_tasks
    self.fetch_tasks(session)
  [Previous line repeated 166 more times]
  File "/app/bot/core/tapper.py", line 266, in fetch_tasks
    self.refresh_token(session)
  File "/app/bot/core/tapper.py", line 389, in refresh_token
    logger.warning(f"{self.session_name} | <yellow>Failed to refresh token:</yellow> {res.text}")
  File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 2052, in warning
    __self._log("WARNING", False, __self._options, __message, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
  File "/usr/local/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "/usr/local/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<title>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 8, in main
    await process()
  File "/app/bot/utils/launcher.py", line 108, in process
    await run_tasks(tg_clients=tg_clients)
  File "/app/bot/utils/launcher.py", line 163, in run_tasks
    await asyncio.gather(*tasks)
  File "/app/bot/core/tapper.py", line 543, in run_tapper
    await Tapper(tg_client=tg_client, multi_thread=True).run(proxy=proxy)
  File "/app/bot/core/tapper.py", line 535, in run
    logger.error(f"{self.session_name} | Unknown error: {error}")
  File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
  File "/usr/local/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
    parser.feed(string)
  File "/usr/local/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<title>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x7fd0960e9a80>
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x7fd0960e9180>

```

Same problem. Last vercion. After restart it works then I gen an error.

**Comment by vanhbakaa** [comment]
Try to use python 3.11.5

**Comment by vanhbakaa** [comment]
Some module are not working correctly

**Comment by DvoeglazovIlya** [comment]
I run throgh docker. I changed version to: 
FROM python:3.11.5-alpine3.18
But I get the same error. And container stoped.

**Comment by DvoeglazovIlya** [comment]
If I start without multi-thread, it worked without stop.
