### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by Tracker878** [vanhbakaa/Fabrika-Friends-Factory#9]
hello
i keep get this in log

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Program Files\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Program Files\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\bot\core\tapper.py", line 451, in run
    if self.login(session):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\bot\core\tapper.py", line 242, in login
    session.options("https://api.ffabrika.com/api/v1/auth/login-telegram", headers=head1)
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\requests\sessions.py", line 613, in options
    return self.request("OPTIONS", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\07.10\Fabrika-Friends-Factory-main\venv\Lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by vanhbakaa** [comment]
It's your internet problem. Connect to the internet and restart the bot
